export default strings = {
    app_name: "HereNow",
    fname: "first name",
    lname: "last name",
    email: "email",
    phone_number: "Phone number",
    password: "password",
    fname_place_holder: "Enter first name",
    lname_place_holder: "Enter last name",
    email_place_holder: "Enter your email",
    phone_place_holder: "Enter your phone number",
    password_place_holder: "Type your password",
    sign_in: "Sign in",
    sign_up: "Sign up",
    facebook: "Facebook",
    google: "Google",
    search: "Search...",
    searching: "Searching...",
    categories: "Categories",
    recents: "Recents",
    description: "Description",
    photo_gallery: "Photo Gallery",
    reset: "Clear All",
    search: "Search",
    apply: "Apply",
    days: "days",
    day: "day",
    remaining: "Remaining",
    featured_deals: "Featured deals",
    deals_we_love: "Deals we love",
    groups_we_love: "Groups we love",
    today_deals: "Today’s deals & events",
    your_wallet: "Your wallet",
    nearby: "Nearby",
    merchants: "Merchants",
    process_paypal: "Using Paypal",
    process_credit_card: "Using Credit Card",
    cancel: "Cancel",
    yes: "Yes",
    purchase_method_message: "Which method you want to process this item?",
    error_missing_field: "Check your inputs again!",
    error_signin_fail: "Can't sign in with your email and password, check your internet connection and try again!",
    error_signup_fail: "Can't sign up with your inputs, maybe your email is used for another account. Please try again!",
    signup_success_title: "Great!",
    signup_success_message: "Your account has been created!",
    address: "Address",
    price: "Price",
    stock: "Stock",
    remaining: "Remaining",
    stock_left: "Seats left",
    fetching: "Fetching...",
    calculating: "Calculating...",
    keywords: "Keywords",
    wallet_empty: "You have no deals in your wallet",
    locations: "Locations",
    submit: "Submit",
    updating: "Updating...",
    no_deal_nearby: "There is no deal around you!",
    ended: "Ended",
    merchant: "Merchant",
    buy_now: "Buy now",
    quantity: "Quantity",
    total_amount: "Total amount",
    phone: "Phone",
    phone_invalid: "Phone number should not shorter than 8 charactors",
    no_today_deals: "There is no deals available at your location",
    no_group: "There is no groups available at yoru location",
    login_cancelled: "Login Cancelled",
    logout: "Logout",
    setting: "Setting",
    logout_confirm_title: "Logout confirmation",
    logout_confirm_message: "Are you sure?",
    wallet_not_loggin_message: "Please login to view your wallet",
    loading_more: "Loading more...",
    no_post: "There is no post around you",
    no_comment: "There is no comment for this post",
    write_comment_place_holder: "Write a comment",
    post_creator: "CREATE NEW POST",
    post_title: "Title",
    post_title_place_holder: "Enter the title",
    post_content: "Content",
    post_content_place_holder: "Fill the content",
    tap_to_change: "Change location",
    book_now: "Buy Now",
    price_title: "from VNĐ",
    overview: "Overview",
    change_to_dark_mode: "Change to dark mode",
    change_dark_mode_confirm_title: "Using Dark Mode",
    change_dark_mode_confirm_message: "The HereNow will shutdown and when you get back, the app will display in dark mode\nShutdown now?",
    change_to_light_mode: "Change to light mode",
    change_light_mode_confirm_title: "Using Light Mode",
    change_light_mode_confirm_message: "The HereNow will shutdown and when you get back, the app will display in light mode\nShutdown now?",
    edit_profile_success: "Your profile have been updated!",
    edit_profile_fail: "Something bad happend, please try again!",
    forgot_password: "forgot your password? Click here!",
    forgot_password_hint: "Submit your email and get the code, use it to reset your password",
    email_not_valid: "Your email is not valid",
    images: "Images",
    deals: "Deals",
    location_content_slogan: "Find travel insights, breaking news, and things to do in this location. Remember to save it for later!",
    shout_out_slogan: "Ask a question, share a cool discovery, find a travel partner, join a party — or simply tell us what’s up!",
    buy_sell_slogan: "Motorbikes, adaptors, travel gear, currency exchange — everything you need for your adventure."
}